/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed": "#002108",
        "on-secondary": "#ffffff",
        "on-background": "#1c1b1b",
        "on-tertiary-fixed-variant": "#00531e",
        "surface-variant": "#e5e2e1",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f3f0ef",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#e7ddff",
        "secondary-fixed-dim": "#e9c400",
        "tertiary-container": "#00742d",
        "tertiary-fixed": "#69ff87",
        "on-secondary-fixed": "#221b00",
        "on-error-container": "#93000a",
        "on-secondary-container": "#6e5c00",
        "secondary-container": "#fcd400",
        "surface-container-high": "#ebe7e7",
        "error-container": "#ffdad6",
        "primary-fixed": "#e7deff",
        "on-error": "#ffffff",
        "on-surface": "#1c1b1b",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#4d00d2",
        "tertiary-fixed-dim": "#3ce36a",
        "on-tertiary-container": "#5eff82",
        "secondary": "#705d00",
        "tertiary": "#005920",
        "inverse-primary": "#ccbdff",
        "on-secondary-fixed-variant": "#544600",
        "surface-container-lowest": "#ffffff",
        "background": "#fcf9f8",
        "outline-variant": "#cac3d9",
        "outline": "#7a7488",
        "on-surface-variant": "#494456",
        "primary": "#5301e0",
        "surface-dim": "#dcd9d9",
        "on-primary-fixed": "#1f0060",
        "surface-container-highest": "#e5e2e1",
        "surface": "#fcf9f8",
        "secondary-fixed": "#ffe16d",
        "surface-tint": "#662ff2",
        "surface-bright": "#fcf9f8",
        "surface-container": "#f0edec",
        "primary-fixed-dim": "#ccbdff",
        "surface-container-low": "#f6f3f2",
        "inverse-surface": "#313030",
        "primary-container": "#6c38f8"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xs": "4px",
        "xl": "40px",
        "md": "16px",
        "sm": "8px",
        "gutter": "24px",
        "margin-desktop": "48px",
        "unit": "4px",
        "margin-mobile": "16px",
        "lg": "24px"
      },
      "fontFamily": {
        "body-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"]
      },
      "fontSize": {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "16px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
