/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "admin-surface": "#121419",
        "admin-surface-dim": "#0a0b0e",
        "admin-surface-bright": "#1a1d24",
        "admin-surface-container-lowest": "#000000",
        "admin-surface-container-low": "#16191f",
        "admin-surface-container": "#1b1e26",
        "admin-surface-container-high": "#232731",
        "admin-surface-container-highest": "#2a2f3a",
        "admin-on-surface": "#f1f3f9",
        "admin-on-surface-variant": "#8b92a5",
        "admin-inverse-surface": "#f1f3f9",
        "admin-inverse-on-surface": "#121419",
        "admin-outline": "#4b5063",
        "admin-outline-variant": "#2b2f3a",
        "admin-surface-tint": "#3b82f6",
        "admin-primary": "#3b82f6",
        "admin-on-primary": "#ffffff",
        "admin-primary-container": "#1d4ed8",
        "admin-on-primary-container": "#eff6ff",
        "admin-inverse-primary": "#2563eb",
        "admin-secondary": "#10b981",
        "admin-on-secondary": "#ffffff",
        "admin-secondary-container": "#047857",
        "admin-on-secondary-container": "#ecfdf5",
        "admin-tertiary": "#f59e0b",
        "admin-on-tertiary": "#ffffff",
        "admin-tertiary-container": "#b45309",
        "admin-on-tertiary-container": "#fffbeb",
        "admin-error": "#ef4444",
        "admin-on-error": "#ffffff",
        "admin-error-container": "#b91c1c",
        "admin-on-error-container": "#fef2f2",
        "admin-background": "#121419",
        "admin-on-background": "#f1f3f9",
        "on-tertiary-fixed": "#002108",
        "on-secondary": "#ffffff",
        "on-background": "#1c1b1b",
        "on-tertiary-fixed-variant": "#00531e",
        "surface-variant": "#241635",
        "error": "#ba1a1a",
        "inverse-on-surface": "#0d0812",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#e2ccff",
        "secondary-fixed-dim": "#e9c400",
        "tertiary-container": "#00742d",
        "tertiary-fixed": "#69ff87",
        "on-secondary-fixed": "#221b00",
        "on-error-container": "#93000a",
        "on-secondary-container": "#e2ccff",
        "secondary-container": "#4a2a7a",
        "surface-container-high": "#2b1b42",
        "error-container": "#ffdad6",
        "primary-fixed": "#e7deff",
        "on-error": "#ffffff",
        "on-surface": "#f8f6f9",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#4d00d2",
        "tertiary-fixed-dim": "#3ce36a",
        "on-tertiary-container": "#5eff82",
        "secondary": "#705d00",
        "tertiary": "#005920",
        "inverse-primary": "#ccbdff",
        "on-secondary-fixed-variant": "#544600",
        "surface-container-lowest": "#0d0812",
        "background": "#110b19",
        "outline-variant": "#3d2b52",
        "outline": "#6b5b7e",
        "on-surface-variant": "#b0a5bd",
        "primary": "#8b3dff",
        "surface-dim": "#180e22",
        "on-primary-fixed": "#1f0060",
        "surface-container-highest": "#392455",
        "surface": "#110b19",
        "secondary-fixed": "#ffe16d",
        "surface-tint": "#8b3dff",
        "surface-bright": "#1f132e",
        "surface-container": "#1f132e",
        "primary-fixed-dim": "#ccbdff",
        "surface-container-low": "#180e22",
        "inverse-surface": "#e5e2e1",
        "primary-container": "#501eb3"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xs": "4px",
        "xl": "40px",
        "md": "16px",
        "sm": "8px",
        "gutter": "24px",
        "margin-desktop": "48px",
        "unit": "4px",
        "margin-mobile": "16px",
        "lg": "24px"
      },
      "fontFamily": {
        "body-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"]
      },
      "fontSize": {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "16px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
